server:
  port: 12300
  shutdown: graceful
  servlet:
    context-path: /fxs
  tomcat:
    threads:
      min-spare: 10
      max: 200
    connection-timeout: 20s

# actuator
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, shutdown, metrics, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false

# encrypt CubeOne
database:
  encrypt-provider: NONE

# spring
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      pool-name: hikaricp-pool
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
  data:
    redis:
      timeout: 10s
      connect-timeout: 10s
      lettuce:
        pool:
          enabled: true
          min-idle: 0
          max-idle: 8
          max-active: 30
          max-wait: 20s
          time-between-eviction-runs: 20s
  rabbitmq:
    connection-timeout: 5s
    template:
      mandatory: true
      receive-timeout: 1s
      reply-timeout: 5s
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1s
        max-interval: 10s

# logging
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: DEBUG

---

# spring
spring:
  config:
    activate:
      on-profile: test
  # datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fxs;MODE=Oracle
    username: sa
    password:
  # jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      sentinel:
        master: mymaster
        nodes: localhost:26379
  # rabbitmq
  rabbitmq:
    addresses: localhost:5672

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j