CREATE TABLE FXS.V1_SEQUENCE_GENERATOR
(
    ID             NUMBER(19)        NOT NULL PRIMARY KEY,
    SYS_CRE_ID     VARCHAR2(30 CHAR) NOT NULL,
    SYS_CRE_DTTM   TIMESTAMP(6)      NOT NULL,
    SYS_UPD_ID     VARCHAR2(30 CHAR),
    SYS_UPD_DTTM   TIMESTAMP(6),
    SEQUENCE_TYPE  VARCHAR2(255 CHAR),
    SEQUENCE_DATE  VARCHAR2(255 CHAR),
    SEQUENCE_VALUE NUMBER(19)
);

CREATE SEQUENCE FXS.V1_SEQUENCE_GENERATOR_SEQ MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOCYCLE;
