CREATE TABLE FXS.V1_KOREAEXIM_EXCHANGE_RATE
(
    ID              NUMBER(19)        NOT NULL PRIMARY KEY,
    SYS_CRE_ID      VARCHAR2(30 CHAR) NOT NULL,
    SYS_CRE_DTTM    TIMESTAMP(6)      NOT NULL,
    SYS_UPD_ID      VARCHAR2(30 CHAR),
    SYS_UPD_DTTM    TIMESTAMP(6),
    BKPR            VARCHAR2(255 CHAR),
    CUR_NM          VARCHAR2(255 CHAR),
    CUR_UNIT        VARCHAR2(255 CHAR),
    DEAL_BAS_R      VARCHAR2(255 CHAR),
    REGISTER_INDEX  NUMBER(10),
    KFTC_BKPR       VARCHAR2(255 CHAR),
    KFTC_DEAL_BAS_R VARCHAR2(255 CHAR),
    REGISTER_DATE   VARCHAR2(255 CHAR),
    RESULT          NUMBER(10),
    TEN_DD_EFEE_R   VARCHAR2(255 CHAR),
    TTB             VARCHAR2(255 CHAR),
    TTS             VARCHAR2(255 CHAR),
    YY_EFEE_R       VARCHAR2(255 CHAR)
);

CREATE SEQUENCE FXS.V1_KOREAEXIM_EXCHANGE_RATE_SEQ MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOCYCLE;